### PR TITLE
release: v1.8.0

### PR DESCRIPTION
**Pull request by newt-sc**

### CODE REVIEW

**Comment by farmaher** [comment]
Hi Buddy - Subscene still not working, Please could you fix it it is the top subtitle service for non-English users.

**Comment by newt-sc** [comment]
@farmaher The tests are passing and even done manual testing for English and Non-English results for Movies and TVShows. It seems to work. However, there were two times that I received a 503 (Service Unavailable) response from Subscene, so I presume the Subscene website is having issues loading occasionally. Will add a simple retry logic for such cases.

**Comment by newt-sc** [comment]
I see there is another issue for Subscene, related to the TVShow searching and the meta for the season year, which is used for matching. Will look into it. Thanks for the report.

**Comment by farmaher** [comment]
I tried V2.0 in search for **Persian** subtitles but no results on Subscene again. Please check these out [HERE](https://streamable.com/8ug2sq) & [HERE](https://streamable.com/4mzvjh). These are the settings in KODI, [HERE](https://ibb.co/JkFkXB2) & [HERE](https://ibb.co/LRZMK9f)

**Comment by newt-sc** [comment]
@farmaher This was a specific Persian language issue. Fixed in v2.1.0.

**Comment by farmaher** [comment]
Many thanks for fixing it, will give it a go.

**Pull request merged**
